Centralize include for gtk 2
With gtk 2, a function prototyle is declared on a wrong way. Depending
on the gcc flags, this will produce an error:
	/usr/include/gtk-2.0/gtk/gtkitemfactory.h:47:1: error: function declaration isn’t a prototype [-Werror=strict-prototypes]

So, move gtk.h include to v4l.h and ensure that this warning is
disabled when including it.

Signed-off-by: Mauro Carvalho Chehab <mchehab+samsung@kernel.org>