filter: get rid of a warning due to a missing prototype
filter.c: In function ‘camorama_filters_init’:
filter.c:574:2: warning: implicit declaration of function ‘camorama_filter_reichardt_get_type’; did you mean ‘camorama_filter_invert_get_type’? [-Wimplicit-function-declaration]
  camorama_filter_reichardt_get_type();
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  camorama_filter_invert_get_type

Signed-off-by: Mauro Carvalho Chehab <mchehab+samsung@kernel.org>